experiment_params:
  quantum_numbers:
    n: 2
    l: 1
    m: 0
  radial_extent: 30

network_params:
  backbone: "FNN"
  layers: [3, 50, 50, 50, 50, 2]
  num_domain: 10000
  num_boundary: 2000

  lrs: [1e-3, 1e-5, 1e-6, 1e-7]
  optimizers: ["adam", "adam", "adam", "adam"]
  epochs: [50000, 50000, 5000, 5000]
  loss_weights: [1,1,1,1,1,1,10,10,1,1,1,1]


prior_params: None

#results_path: "/Users/lat/Desktop/Code/pinns-experiments/schrodinger_equation/results_TISE_hydrogen_without_decomposition/"
results_path:  "../../../../../dccstor/pinns/results/results_TISE_hydrogen_without_decomposition/"